name: report_incident
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  easy_localization: ^3.0.2
  equatable: ^2.0.5
  fade_shimmer: ^2.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_image_compress: ^2.0.4
  flutter_map: ^5.0.0
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.0.9
  geolocator: ^9.0.2
  google_fonts: ^5.1.0
  http: ^1.1.0
  image_picker: ^1.0.2
  intl: ^0.18.0
  latlong2: ^0.9.0
  lottie: ^2.6.0
  multi_image_picker_view: ^0.0.17
  package_info_plus: ^4.0.2
  page_transition: ^2.0.9
  permission_handler: ^10.4.3
  persistent_bottom_nav_bar_v2: ^4.2.8
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_gen:
  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/l10n/
